Vagrant.configure("2") do |config|
  config.vm.box = "metabarj0/Box4Docker"
  config.vm.box_version = "1.0.0"
  config.vbguest.auto_update = false
  config.vm.box_check_update = false
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8192"
    vb.cpus = "8"
  end

  config.ssh.username = "docker"
  config.ssh.password = "docker"
  config.ssh.keep_alive = "true"
end
