Vagrant.configure("2") do |config|

  # environmental settings
  $cpu=ENV.fetch('BOX4DOCKER_CPU', 1)
  $memory=ENV.fetch('BOX4DOCKER_MEM', 1024)
  $vram=ENV.fetch('BOX4DOCKER_VRAM', 16)

  config.vm.define "Box4Docker" do |box4docker|
    box4docker.vm.box = "metabarj0/Box4Docker"
    box4docker.vm.box_version = "1.1.0"
    box4docker.vm.box_check_update = false

    box4docker.vm.provider "virtualbox" do |vb|
      vb.customize ['modifyvm', :id, '--memory', $memory]
      vb.customize ['modifyvm', :id, '--cpus', $cpu]
      vb.customize ["modifyvm", :id, "--vram", $vram]
    end
  end

  config.vbguest.auto_update = false

  config.ssh.username = "docker"
  config.ssh.password = "docker"
  config.ssh.keep_alive = "true"
  config.ssh.forward_agent = "true"
end
