Vagrant.configure("2") do |config|

  # environmental settings
  $cpu=ENV.fetch('BOX4DOCKER_CPU', 8)
  $memory=ENV.fetch('BOX4DOCKER_MEM', 8192)
  $vram=ENV.fetch('BOX4DOCKER_VRAM', 16)

  config.vm.box = "metabarj0/Box4Docker"
  config.vm.box_version = "1.0.0"
  config.vbguest.auto_update = false
  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |vb|
    vb.customize ['modifyvm', :id, '--memory', $memory]
    vb.customize ['modifyvm', :id, '--cpus', $cpu]
    vb.customize ["modifyvm", :id, "--vram", $vram]
  end

  config.ssh.username = "docker"
  config.ssh.password = "docker"
  config.ssh.keep_alive = "true"
end
