#!/bin/sh

if [ -z "$1" ]; then
  echo 'Expecting a package...exiting...'
  exit 1
fi

# testing the package
tar -tf "$1" 2> /dev/null 1> /dev/null

if [ ! $? -eq 0 ]; then
  echo 'Invalid or corrupted package...exiting...'
  exit 1
fi

# extracting the package and cleanup
tar --directory / -xf "$1" && rm -f "$1"
