version: '3.2'

services:
  # mysql server
  mysql:
    image: metabarj0/devenv_trinitycore_mysql

    networks:
      backend:

    expose:
      - "3306"

    # grabbed from the mysql image EXTRA_DOCKERFILE_COMMANDS in the manifest
    volumes:
      - type: volume
        source: mysql_data
        target: /usr/local/mysql/data
      - type: volume
        source: mysql_conf
        target: /usr/local/mysql/etc
      - type: volume
        source: mysql_mysql-files
        target: /usr/local/mysql/mysql-files

    # grabbed from the mysql image EXTRA_DOCKERFILE_COMMANDS in the manifest
    entrypoint:
      - sh
      - -c
      - /usr/local/mysql/mysql_server_start.sh

    # grabbed from the mysql image EXTRA_DOCKERFILE_COMMANDS in the manifest
    environment:
      - TERMINFO=/usr/local/share/terminfo

  shell:
    depends_on:
      - mysql

    image: metabarj0/devenv_trinitycore_shell

    networks:
      backend:

    # exposed to host
    ports:
      - "8085:8085"
      - "3724:3724"

    volumes:
      # the metabarj0/docker-cli (base image of this service) need that bind
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      # home folder for devenv_trinitycore
      - type: volume
        source: devenv_trinitycore_home
        target: /home/devenv_trinitycore
      # vim conf
      - type: volume
        source: devenv_trinitycore_.vim
        target: /home/devenv_trinitycore/.vim
      # ssh keys and conf
      - type: volume
        source: devenv_trinitycore_.ssh
        target: /home/devenv_trinitycore/.ssh
      # codebases
      - type: volume
        source: devenv_trinitycore_src
        target: /home/devenv_trinitycore/src
      # built files staging area
      - type: volume
        source: devenv_trinitycore_build
        target: /home/devenv_trinitycore/build
      # debug version of trinitycore binaries
      - type: volume
        source: devenv_trinitycore_debug
        target: /home/devenv_trinitycore/debug
      # release version of trinitycore binaries
      - type: volume
        source: devenv_trinitycore_release
        target: /home/devenv_trinitycore/release
      # deployed version of trinitycore binaries (may be release or debug)
      - type: volume
        source: devenv_trinitycore_deploy
        target: /usr/local/trinitycore
      # same data volume shared amongst debug and release builds
      - type: volume
        source: devenv_trinitycore_data
        target: /home/devenv_trinitycore/debug/share/data
      - type: volume
        source: devenv_trinitycore_data
        target: /home/devenv_trinitycore/release/share/data
      # debug log
      - type: volume
        source: devenv_trinitycore_debug_log
        target: /home/devenv_trinitycore/debug/var/log
      # release log
      - type: volume
        source: devenv_trinitycore_release_log
        target: /home/devenv_trinitycore/release/var/log

    # login entrypoint, parse .bash_profile
    entrypoint :
      - bash
      - --login
      - -c
      - /usr/local/bin/devenv_shell_entrypoint.sh

    # the container still runs, even if launched in detached mode. to interact,
    # one has to attach to it
    stdin_open: true
    tty: true
    logging:
      driver: 'none'

    # allows gdb to be used
    cap_add:
      - SYS_PTRACE

    # dev tools need this environment
    environment:
      - TERMINFO=/usr/local/share/terminfo
      - TERM=xterm-256color
      - GIT_EXEC_PATH=/usr/local/libexec/git-core/

volumes:
  # shell related volumes
  devenv_trinitycore_home:
  devenv_trinitycore_.vim:
  devenv_trinitycore_.ssh:
  devenv_trinitycore_src:
  devenv_trinitycore_build:
  devenv_trinitycore_debug:
  devenv_trinitycore_release:
  devenv_trinitycore_deploy:
  devenv_trinitycore_data:
  devenv_trinitycore_debug_log:
  devenv_trinitycore_release_log:

  # mysql related volumes
  mysql_data:
  mysql_conf:
  mysql_mysql-files:

networks:
  # a network shared between the shell and mysql
  backend:
