#!/bin/sh

bootstrap_fetchInStagingArea() {
  cp -r "$CARRIER_SHARE_BOOTSTRAP_DIR" "$CARRIER_TMP_DIR"
}

bootstrap_fetchLibInStagingArea() {
  cp "$CARRIER_LIB_DIR"/exportPackageTo \
     "$CARRIER_LIB_DIR"/importPackageFrom \
     "$CARRIER_LIB_DIR"/functions.sh \
     "$CARRIER_TMP_DIR"/bootstrap
}

bootstrap_build() {
  cd "$CARRIER_TMP_DIR"/bootstrap

  docker build --squash -t metabarj0/bootstrap .
  docker image prune -f

  cd - 1> /dev/null
}

bootstrap_run() {
  # need some functions
  . "$CARRIER_TMP_DIR"/bootstrap/functions.sh

  cat << EOI
Specify the version of GCC you want to build. Note that today, only 7.2.0
and 7.3.0 are supported : [7.3.0]
EOI

  local gcc_version="$(readValueWithDefault '7.3.0')"

  cat << EOI
Specify the binutils version you want to build. Note that for GCC 7.3.0, 2.29
is a working version : [2.29]
EOI

  local binutils_version="$(readValueWithDefault '2.29')"

  cat << EOI
Specify the version of Kernel headers you want to use. Note that for GCC 7.3.0
the 4.14.3 version works perfectly well. Moreover, only version 4+ is
supported : [4.14.14]
EOI

  local kernel_version="$(readValueWithDefault '4.14.14')"

  cat << EOI
Specify the make version you want to use. Note that version 4.2 is
good : [4.2]
EOI

  local make_version="$(readValueWithDefault '4.2')"

  # run the bootstrap image
  docker run --rm -it \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -e GCC_VERSION="$gcc_version" \
    -e BINUTILS_VERSION="$binutils_version" \
    -e KERNEL_VERSION="$kernel_version" \
    -e MAKE_VERSION="$make_version" \
    metabarj0/bootstrap

  cat << EOI
Bootstrapping successfully done! Would you like to remove the
metabarj0/bootstrap docker image? [Y/n]
EOI

 local remove_bootstrap="$(readValueWithDefault 'Y')"

 if [ $remove_bootstrap = 'Y' ] || [ $remove_bootstrap = 'y' ]; then
 docker rmi metabarj0/bootstrap
 fi
}

bootstrap_cleanupStagingArea() {

  rm -rf "$CARRIER_TMP_DIR"/bootstrap
}

bootstrap_fetchInStagingArea
bootstrap_fetchLibInStagingArea
bootstrap_build
bootstrap_run
bootstrap_cleanupStagingArea
