#!/bin/sh

if [ -z "$1" ]; then
  echo 'Expecting a destination for the package...exiting...'
  exit 1
fi

package_directory="$(dirname "$1")"
package_file_name="$(basename "$1")"

mkdir -p "$package_directory"

# create a tar archive in destination, no more, no less
tar \
  -cf "$package_directory"/"$package_file_name" \
  --no-recursion \
  $(cat /image.dist)
